"""
Hybrid fusion model configuration.

One reproducible place for the fusion task definition, feature groups,
split fractions, hyperparameters, and artifact paths.

Two alignment decisions are encoded here and explained in
docs/hybrid_ai_architecture.md:

- **Temporal**: the Phase 3 tabular model forecasts day T+1 from day-T
  conditions; the Phase 4 vision model classifies day T from the day-T
  scene. The fusion target is the **T+1** region-day category, matching
  the early-warning mission. Both models' day-T outputs are therefore
  evidence *about tomorrow* — the satellite branch contributes current
  convective state, not a same-day answer.
- **Spatial**: weather records are per point, imagery is per region.
  Everything is aggregated to the region-day, the level the satellite
  labels were built at.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

# ai_models/fusion_model/config.py -> ai_models -> repository root
REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class FusionConfig:
    # --- Inputs (produced by Phases 2-4) ---
    weather_dataset_path: Path = REPO_ROOT / "data/processed/datasets/training_dataset.parquet"
    satellite_features_path: Path = REPO_ROOT / "data/processed/features/satellite_features.parquet"
    validation_report_path: Path = REPO_ROOT / "data/metadata/validation_report.txt"
    saved_models_dir: Path = REPO_ROOT / "ai_models/saved_models"

    # --- Outputs ---
    experiments_dir: Path = REPO_ROOT / "ai_models/experiments"
    reports_dir: Path = REPO_ROOT / "reports"
    unified_dataset_path: Path = REPO_ROOT / "data/processed/datasets/fusion_dataset.parquet"

    # --- Feature groups -------------------------------------------------
    #: Region-day means of the Phase 2 weather variables.
    weather_features: tuple[str, ...] = (
        "temperature_c",
        "humidity_pct",
        "pressure_hpa",
        "wind_speed_ms",
        "wind_direction_deg",
        "cloud_cover_pct",
    )
    #: Historical rainfall aggregation windows (days), region-level, past-only.
    rain_windows: tuple[int, ...] = (1, 3, 7, 30)
    #: Interpretable scene statistics from Phase 4 preprocessing.
    satellite_features: tuple[str, ...] = (
        "cloud_density",
        "brightness_mean",
        "brightness_std",
        "spatial_dispersion",
        "cold_top_fraction",
        "cloud_growth_rate",
        "valid_fraction",
    )
    #: Upstream model outputs used as fusion inputs (Approach 1 and 2).
    score_features: tuple[str, ...] = ("weather_risk_score", "satellite_risk_score")

    # --- Task ---
    target_column: str = "target_category"
    num_classes: int = 3
    label_names: dict[int, str] = field(
        default_factory=lambda: {0: "Normal", 1: "Heavy", 2: "Extreme"}
    )
    #: Human-facing event names for the prediction payload.
    event_names: dict[int, str] = field(
        default_factory=lambda: {
            0: "No Extreme Rainfall",
            1: "Heavy Rainfall",
            2: "Extreme Rainfall",
        }
    )

    # --- Split (chronological; consistent with Phases 3 and 4) ---
    train_fraction: float = 0.70
    validation_fraction: float = 0.15

    # --- Out-of-fold generation of the weather branch --------------------
    # The Phase 3 artifact was fitted on most of the fusion period, so its
    # score is memorised there (measured AUC 1.000 in-sample vs 0.875
    # out-of-sample). Training a fusion model on that feature teaches it to
    # threshold a value that will not exist at serving time. The weather
    # score is therefore regenerated by walk-forward retraining: each fold
    # is scored by an estimator fitted only on strictly earlier days.
    oof_folds: int = 6
    #: Earliest fraction of the record reserved as the first training block;
    #: region-days inside it get no out-of-fold score and leave the dataset.
    oof_warmup_fraction: float = 0.15

    # --- Training ---
    random_seed: int = 42
    model_version: str = "v1"
    selection_metric: str = "f1_macro"
    good_f1_macro: float = 0.60

    #: Weight grid for Approach 1 (weather weight; satellite gets 1 - w).
    weight_grid_step: float = 0.05

    # --- Neural fusion network (Approach 3) ---
    nn_hidden_weather: int = 32
    nn_hidden_satellite: int = 16
    nn_hidden_fusion: int = 32
    nn_dropout: float = 0.3
    nn_epochs: int = 120
    nn_learning_rate: float = 3e-3
    nn_weight_decay: float = 1e-4
    nn_batch_size: int = 32

    # --- Confidence estimation weights (must sum to 1.0) ---
    confidence_weight_probability: float = 0.5
    confidence_weight_agreement: float = 0.3
    confidence_weight_similarity: float = 0.2

    # --- Risk level thresholds on P(heavy or extreme) ---
    risk_low_max: float = 0.25
    risk_moderate_max: float = 0.50
    risk_high_max: float = 0.75

    def ensure_output_dirs(self) -> None:
        for path in (
            self.saved_models_dir,
            self.experiments_dir,
            self.reports_dir,
            self.unified_dataset_path.parent,
        ):
            path.mkdir(parents=True, exist_ok=True)

    def feature_columns(self) -> list[str]:
        """Full feature-level fusion vector (Approach 2 and 3)."""
        return (
            list(self.weather_features)
            + [f"rain_sum_{w}d" for w in self.rain_windows]
            + ["rain_trend_3d", "season_sin", "season_cos"]
            + list(self.satellite_features)
            + list(self.score_features)
        )

    def weather_probability_columns(self) -> list[str]:
        """Phase 3 class-probability vector stored per region-day (Approach 1)."""
        return [f"weather_prob_{c}" for c in range(self.num_classes)]

    def satellite_probability_columns(self) -> list[str]:
        """Phase 4 class-probability vector stored per region-day (Approach 1)."""
        return [f"satellite_prob_{c}" for c in range(self.num_classes)]

    def weather_feature_columns(self) -> list[str]:
        """Weather branch of the neural fusion encoder."""
        return (
            list(self.weather_features)
            + [f"rain_sum_{w}d" for w in self.rain_windows]
            + ["rain_trend_3d", "season_sin", "season_cos", "weather_risk_score"]
        )

    def satellite_feature_columns(self) -> list[str]:
        """Satellite branch of the neural fusion encoder."""
        return list(self.satellite_features) + ["satellite_risk_score"]


FUSION_BUNDLE_TEMPLATE = "varuna_fusion_model_{version}.pkl"
MODEL_INFO_FILENAME = "model_info.json"
